# Header Menu
menu:
  Home: /
#  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
#  Contact: /contact/
#  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/Azuredrop
  twitter: https://twitter.com/drop_azure
  rss: atom.xml

# Miscellaneous
color_scheme: turquoise   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: computerlab_ # twitter username without the @
default_author: AzureDrop

about: 欢迎光临
phone: 716-472-4484
email: taozhanbiao@gmail.com
address_1: 140 Metropolitan Avenue
address_2: 5th Floor
address_3: Brooklyn, NY 11249
skype: ptsteadman
lat: 40.715911 
long: -73.962147
